### PR TITLE
Fixed sign up page and functionality

### PR DESCRIPTION
**Pull request by rmevorac**

### CODE REVIEW

**Comment by vinayr01** [comment]
It looks good to me. The only comment would be on where you fetch.
I believe there is no POST call yet on the backend to add a new user via the sign-up page, so the URL on the backend for the POST request will need to match what u have if it ever gets created (or vice versa)

**Comment by rmevorac** [comment]
Yes that is correct. I was working on the backend part today as well, but I don't think it will be done in time.

**Comment by zachary-silver** [comment]
Hey Roey, looks good except for the commented out createUser function. I understand you probably did that because there's no back end call implemented yet, but you should have the function operate accordingly if an error occurs (like a failed call to the backend) anyways. Even if it's just console logging an error. Doing that is probably better than pushing what is essentially "dead code" to the repository.

**Comment by rmevorac** [comment]
Fixed the merge conflict and uncommented the createUser function. Should be good to merge now

**Pull request merged**
