### PR TITLE
Garrett database

### PR DESCRIPTION
**Pull request by Garrett-Ravatt**
adds database connection and methods for requesting post data.

### CODE REVIEW

**Comment by vinayr01** [comment]
For clarification: what's the difference between using the function "harsh_jsonify" and "jsonify"?

**Review by zachary-silver — APPROVED** [review]
Nice work Garrett, I can easily tell what's going on with the code you've written. 

One thing to note though is that while changing the origins to the wildcard on line 46 accomplished what you want for now, it won't work as soon as this code is implemented with the front end. CORS doesn't allow passing credentials in any form (ie. cookies) which is what we need for session management when origins is set to the wildcard (or allow any) for security purposes.

This is fine for now because we should probably have whatever we put there be an environment variable along with multiple other places. But we'll sort that out soon.

**Review by rmevorac — APPROVED** [review]
This is a great template for any future database linking

**Comment by Garrett-Ravatt** [comment]
> For clarification: what's the difference between using the function "harsh_jsonify" and "jsonify"?

We use ObjectID in our database structure, which is not compatible with jsonify. harsh_jsonify is used where jsonify would usually error, and is compatible with all our data types.

**Pull request merged**
